name: Deploy InfoBytes Backend

on:
  create:
    tags:
      - "*"

jobs:
  upload:
    name: Upload to EC2 from tag branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.INFOBYTE_EC2_PEM_FILE }}
          REMOTE_HOST: ${{ secrets.INFOBYTE_REMOTE_HOST }}
          REMOTE_USER: ubuntu
          TARGET: /home/ubuntu/infobyte
          EXCLUDE: "/frontend/, /backend/node_modules/, /backend/dist/"

    build:
      name: Build And Run
      runs-on: ubuntu-latest
      steps:
        - name: Executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.INFOBYTE_REMOTE_HOST }}
            username: ubuntu
            key: ${{ secrets.INFOBYTE_EC2_PEM_FILE }}
            script: |
              cd ~/infobyte/backend
              yarn
              prisma migrate deploy
              yarn build
              yarn start:prod
